"""Core library for CareerOS."""

from .ai import (
    AIError,
    AIProvider,
    AIResponseError,
    MockAIProvider,
    OllamaProvider,
    OpenAIProvider,
    SUPPORTED_PROVIDERS,
    create_ai_provider,
)
from .measurability import is_measurable
from .artifact_templates import (
    TemplateRegistry,
    default_template_registry,
)
from .exceptions import (
    CareerOSException,
    EntityNotFoundError,
    RepositoryError,
    SchemaLoadError,
    ValidationError,
)
from .models import EntityRecord, ValidationResult
from .export_contract import ExportContract, ExportContractBuilder, ExportSource
from .evidence_selector import EvidenceSelector
from .generators import (
    DocxCVGenerator,
    DocxPreparationGuideGenerator,
    GeneratorRegistry,
    MarkdownCoverLetterGenerator,
    MarkdownCVGenerator,
    MarkdownPreparationGuideGenerator,
    default_generator_registry,
)
from .profile_loader import ProfileLoader
from .pipelines import generate_artifact, generate_markdown_cv, generate_tailored_artifact
from .repository import FileSystemRepository
from .schema_loader import SchemaLoader
from .validator import EntityValidator
from .optimizer import CVOptimizer, OptimizationResult, OptimizationStatus, OptimizationSummary, Recommendation, RequirementConcept, CONCEPT_TAXONOMY
from .docx_renderer import CVDocumentRenderer
from .recommendation_applier import RecommendationApplier
from .resolution import (
    AchievementNotMeasurableError,
    InvalidAchievementError,
    RESOLVABLE_RULES,
    ResolutionError,
    ResolutionTargetNotFoundError,
    UnsupportedRuleError,
    apply_resolution,
)
from .interview import (
    AnswerEvaluation,
    CATEGORY_ORDER,
    QUESTION_TEMPLATES,
    Competency,
    CompetencyMapper,
    EvidenceCitation,
    InterviewAnswer,
    InterviewEngine,
    InterviewError,
    InterviewFeedback,
    InterviewPlan,
    InterviewQuestion,
    InterviewQuestionInstance,
    InterviewReport,
    InterviewSession,
    InterviewSessionError,
    InterviewSummary,
    InvalidAnswerError,
    InvalidProfileError,
    InvalidSessionStateError,
    PreparationGuide,
    QuestionBuilder,
    QuestionTemplate,
    QuestionType,
    SessionMetrics,
    SessionState,
    SuggestedAnswer,
    UnsupportedQuestionTypeError,
    build_preparation_plan,
    template_for,
    templates_for,
)

from .acquisition import (
    AcquisitionPipeline,
    CanonicalProfileBuilder,
    DocumentReader,
    LLMExtractor,
    OpenAILLMExtractor,
    OllamaLLMExtractor,
    LLMConfigurationError,
    create_llm_extractor,
    PersonData,
    TextExtractor,
    YamlWriter,
)

__all__ = [
    "CareerOSException",
    "AIError",
    "AIProvider",
    "AIResponseError",
    "MockAIProvider",
    "OllamaProvider",
    "OpenAIProvider",
    "SUPPORTED_PROVIDERS",
    "create_ai_provider",
    "is_measurable",
    "EntityNotFoundError",
    "EntityRecord",
    "EntityValidator",
    "ExportContract",
    "ExportContractBuilder",
    "ExportSource",
    "EvidenceSelector",
    "FileSystemRepository",
    "GeneratorRegistry",
    "default_generator_registry",
    "DocxCVGenerator",
    "DocxPreparationGuideGenerator",
    "generate_artifact",
    "generate_markdown_cv",
    "generate_tailored_artifact",
    "MarkdownCoverLetterGenerator",
    "MarkdownCVGenerator",
    "MarkdownPreparationGuideGenerator",
    "ProfileLoader",
    "RepositoryError",
    "SchemaLoader",
    "SchemaLoadError",
    "ValidationError",
    "ValidationResult",
    "CVOptimizer",
    "OptimizationResult",
    "OptimizationStatus",
    "OptimizationSummary",
    "Recommendation",
    "RequirementConcept",
    "CONCEPT_TAXONOMY",
    "CVDocumentRenderer",
    "RecommendationApplier",
    "ResolutionError",
    "UnsupportedRuleError",
    "ResolutionTargetNotFoundError",
    "InvalidAchievementError",
    "AchievementNotMeasurableError",
    "RESOLVABLE_RULES",
    "apply_resolution",
    "TemplateRegistry",
    "default_template_registry",
    "AcquisitionPipeline",
    "CanonicalProfileBuilder",
    "DocumentReader",
    "LLMExtractor",
    "OpenAILLMExtractor",
    "OllamaLLMExtractor",
    "LLMConfigurationError",
    "create_llm_extractor",
    "PersonData",
    "TextExtractor",
    "YamlWriter",
    "AnswerEvaluation",
    "InterviewAnswer",
    "InterviewEngine",
    "InterviewFeedback",
    "InterviewQuestionInstance",
    "InterviewReport",
    "InterviewSession",
    "InterviewSessionError",
    "InterviewSummary",
    "InvalidAnswerError",
    "InvalidSessionStateError",
    "SessionMetrics",
    "SessionState",
    "build_preparation_plan",
    "CompetencyMapper",
    "QuestionBuilder",
    "QuestionType",
    "CATEGORY_ORDER",
    "Competency",
    "EvidenceCitation",
    "InterviewPlan",
    "InterviewQuestion",
    "PreparationGuide",
    "SuggestedAnswer",
    "QuestionTemplate",
    "QUESTION_TEMPLATES",
    "template_for",
    "templates_for",
    "InterviewError",
    "InvalidProfileError",
    "UnsupportedQuestionTypeError",
]
