"""Interview Intelligence — domain models.

Strongly-typed, immutable models owned by the Interview Intelligence module
(see ``docs/platform-beta/interview-intelligence/01-domain-model.md``).

Ownership rules honored here:
- Module objects never become the source of truth for professional facts.
- References to canonical profile elements use the ADR-002 reference contract
  (``{id, type}``) through ``EvidenceCitation.source_ref()``.
- ``Competency`` is a *view* over canonical skills + the Core concept taxonomy
  (``CONCEPT_TAXONOMY``), never a parallel skill registry.
- ``SuggestedAnswer`` is structured guidance (Situation/Task/Action/Result/
  Evidence/Achievement) that a future LLM layer turns into prose — never prose
  generated by this deterministic engine.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class QuestionType(str, Enum):
    """Deterministic question categories (M1.14)."""

    TECHNICAL = "technical"
    BEHAVIORAL = "behavioral"
    LEADERSHIP = "leadership"
    PROJECT_DEEP_DIVE = "project_deep_dive"
    PROBLEM_SOLVING = "problem_solving"
    CAREER_MOTIVATION = "career_motivation"


CATEGORY_ORDER: tuple[QuestionType, ...] = (
    QuestionType.TECHNICAL,
    QuestionType.BEHAVIORAL,
    QuestionType.LEADERSHIP,
    QuestionType.PROJECT_DEEP_DIVE,
    QuestionType.PROBLEM_SOLVING,
    QuestionType.CAREER_MOTIVATION,
)


@dataclass(frozen=True)
class EvidenceCitation:
    """A grounded reference to a canonical profile element (ADR-002).

    ``quote`` is a verbatim excerpt from the profile element — never internal
    reasoning metadata. This is what makes a generated question evidence-backed.
    """

    element_type: str
    element_id: str
    quote: str | None = None

    def source_ref(self) -> dict[str, str]:
        """The ADR-002 reference contract ``{id, type}``."""
        return {"id": self.element_id, "type": self.element_type}

    def to_dict(self) -> dict[str, Any]:
        return {
            "elementType": self.element_type,
            "elementId": self.element_id,
            "quote": self.quote,
        }


@dataclass(frozen=True)
class SuggestedAnswer:
    """Deterministic answer outline for a question.

    The outline guides the candidate (and a future LLM rephrasing layer) without
    fabricating content: each component is either sourced from the canonical
    profile or left unset. ``evidence`` always carries the citations that ground
    the outline.
    """

    situation: str | None = None
    task: str | None = None
    action: str | None = None
    result: str | None = None
    evidence: tuple[EvidenceCitation, ...] = ()
    achievement: str | None = None

    @property
    def has_content(self) -> bool:
        return bool(
            self.situation
            or self.task
            or self.action
            or self.result
            or self.achievement
            or self.evidence
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "situation": self.situation,
            "task": self.task,
            "action": self.action,
            "result": self.result,
            "evidence": [citation.to_dict() for citation in self.evidence],
            "achievement": self.achievement,
        }


@dataclass(frozen=True)
class Competency:
    """A capability identifier — a deterministic view over canonical skills.

    ``skill_ids`` reference canonical profile skills; ``concept_ids`` reference
    Core ``CONCEPT_TAXONOMY`` ids. ``evidence`` cites the canonical elements
    that substantiate the competency (the skill and the experiences that use it).
    """

    id: str
    name: str
    category: str
    skill_ids: tuple[str, ...] = ()
    concept_ids: tuple[str, ...] = ()
    evidence: tuple[EvidenceCitation, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "category": self.category,
            "skill_ids": list(self.skill_ids),
            "concept_ids": list(self.concept_ids),
            "evidence": [citation.to_dict() for citation in self.evidence],
        }


@dataclass(frozen=True)
class InterviewQuestion:
    """A typed, self-contained interview question bound to profile context."""

    id: str
    category: QuestionType
    text: str
    competency_ids: tuple[str, ...] = ()
    context_refs: tuple[dict[str, str], ...] = ()
    evidence_citations: tuple[EvidenceCitation, ...] = ()
    difficulty: str = "intermediate"
    motivation: str | None = None
    template_id: str | None = None
    suggested_answer: SuggestedAnswer | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "category": self.category.value,
            "text": self.text,
            "competency_ids": list(self.competency_ids),
            "context_refs": [dict(ref) for ref in self.context_refs],
            "evidence_citations": [
                citation.to_dict() for citation in self.evidence_citations
            ],
            "difficulty": self.difficulty,
            "motivation": self.motivation,
            "template_id": self.template_id,
            "suggested_answer": (
                self.suggested_answer.to_dict() if self.suggested_answer else None
            ),
        }


@dataclass(frozen=True)
class InterviewPlan:
    """Deterministic output of the interview engine.

    The plan is structured so a future AI layer can enrich question text and
    suggested-answer prose without redesign: every question is evidence-backed
    and every outline is already structured (Situation/Task/Action/Result/
    Evidence/Achievement).
    """

    profile_version: str
    person_id: str
    competencies: tuple[Competency, ...] = ()
    questions: tuple[InterviewQuestion, ...] = ()
    target_role: str | None = None
    target_context_id: str | None = None
    target_role_requirements: tuple[str, ...] = ()
    derived_from_profile_version: str = ""

    @property
    def question_count(self) -> int:
        return len(self.questions)

    def questions_by_category(self) -> dict[str, tuple[InterviewQuestion, ...]]:
        grouped: dict[str, list[InterviewQuestion]] = {}
        for question in self.questions:
            grouped.setdefault(question.category.value, []).append(question)
        return {category: tuple(items) for category, items in grouped.items()}

    def to_dict(self) -> dict[str, Any]:
        return {
            "profile_version": self.profile_version,
            "person_id": self.person_id,
            "target_role": self.target_role,
            "target_context_id": self.target_context_id,
            "target_role_requirements": list(self.target_role_requirements),
            "derived_from_profile_version": self.derived_from_profile_version,
            "competencies": [competency.to_dict() for competency in self.competencies],
            "questions": [question.to_dict() for question in self.questions],
        }

    def to_json(self, indent: int = 2) -> str:
        import json

        return json.dumps(self.to_dict(), indent=indent, default=str)


@dataclass(frozen=True)
class PreparationGuide:
    """Candidate-facing grouping of plan questions (document artifact, future).

    Produced from a plan; the actual document rendering (via ``ExportContractBuilder``
    + a registered template) is deferred to the document milestone (M1.15).
    """

    id: str
    profile_id: str
    target_role: str | None = None
    competencies: tuple[Competency, ...] = ()
    questions: tuple[InterviewQuestion, ...] = ()

    @classmethod
    def from_plan(cls, plan: InterviewPlan, guide_id: str) -> "PreparationGuide":
        return cls(
            id=guide_id,
            profile_id=plan.person_id,
            target_role=plan.target_role,
            competencies=plan.competencies,
            questions=plan.questions,
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "profile_id": self.profile_id,
            "target_role": self.target_role,
            "competencies": [competency.to_dict() for competency in self.competencies],
            "questions": [question.to_dict() for question in self.questions],
        }
